package xyz.znix.xftl.vanillasave

import xyz.znix.xftl.game.InGameState
import xyz.znix.xftl.sector.Beacon
import xyz.znix.xftl.sector.Sector

/**
 * Applies a parsed vanilla save's per-beacon state onto a freshly generated
 * [Sector], matching beacons by index. Our beacon layout is generated by our
 * own algorithm (vanilla's exact generator isn't public), so the map's
 * geometry differs from the original run - but every bit of per-beacon STATE
 * (visits, stores, enemies, quests, fleet presence) is restored, which is
 * what the run consists of.
 */
object VanillaSaveApplier {
    fun applyBeacons(data: VanillaSaveData, sector: Sector, game: InGameState) {
        sector.fleetAdvanceModifier = data.pursuitMod
        sector.dangerZoneCentre.x = data.fleetOffset
        sector.dangerZoneCentre.y = data.fleetFudge

        for ((index, vb) in data.beacons.withIndex()) {
            val beacon: Beacon = sector.beacons.getOrNull(index) ?: break

            beacon.visited = vb.visitCount > 0
            if (vb.fleetPresence > 0) {
                beacon.isOvertaken = true
            }

            // Enemy-holding beacons store the event that spawns the ship.
            // Jumping to such a beacon re-runs the event, like vanilla
            // re-running its ship event.
            if (vb.enemyPresent) {
                game.eventManager.getByDeserialisationIdOrNull(vb.shipEventId)?.let { beacon.event = it }
            }

            if (vb.storePresent && vb.store != null) {
                beacon.hasStore = true
                beacon.setStoreData(buildStore(vb.store!!, game))
            }
        }

        // Quests parked on beacons
        for ((eventId, beaconId) in data.questEvents) {
            val beacon = sector.beacons.getOrNull(beaconId)
            val event = game.eventManager.getByDeserialisationIdOrNull(eventId)
            if (event == null) {
                continue
            }
            if (beacon != null && !beacon.visited) {
                beacon.hasQuest = true
                beacon.event = event
            } else {
                game.addDelayedQuest(event)
            }
        }

        // Quests delayed to the next sector
        for (eventId in data.distantQuests) {
            game.eventManager.getByDeserialisationIdOrNull(eventId)?.let { game.addDelayedQuest(it) }
        }
    }

    private fun buildStore(store: VanillaSaveData.VanillaStore, game: InGameState): xyz.znix.xftl.game.StoreData {
        val result = xyz.znix.xftl.game.StoreData()
        result.availableResources.fuel = store.fuel
        result.availableResources.missiles = store.missiles
        result.availableResources.droneParts = store.droneParts

        for (shelf in store.shelves) {
            for (item in shelf.items) {
                // xftl models a store section as a list with nulls for
                // sold-out slots; vanilla marks them avail=0 with the name
                // preserved (the name is lost in our model).
                addShelfItem(result, shelf.type, item, game)
            }
        }
        return result
    }

    private fun addShelfItem(
        result: xyz.znix.xftl.game.StoreData,
        shelfType: Int,
        item: VanillaSaveData.VanillaItem,
        game: InGameState
    ) {
        if (!item.available) {
            // Sold out: keep the slot, but empty.
            addNull(result, shelfType)
            return
        }
        if (item.name.isEmpty()) {
            addNull(result, shelfType)
            return
        }
        val bp = game.blueprintManager.getOrNull(item.name)
        when (shelfType) {
            VanillaSaveFormat.SHELF_SYSTEM -> result.systems.add(bp as? xyz.znix.xftl.systems.SystemBlueprint)
            VanillaSaveFormat.SHELF_WEAPON -> result.weapons.add(bp as? xyz.znix.xftl.weapons.AbstractWeaponBlueprint)
            VanillaSaveFormat.SHELF_DRONE -> result.drones.add(bp as? xyz.znix.xftl.weapons.DroneBlueprint)
            VanillaSaveFormat.SHELF_AUGMENT -> result.augments.add(bp as? xyz.znix.xftl.augments.AugmentBlueprint)
            VanillaSaveFormat.SHELF_CREW -> {
                val race = bp as? xyz.znix.xftl.crew.CrewBlueprint
                result.crew.add(race?.let { xyz.znix.xftl.crew.LivingCrewInfo.generateRandom(it, game) })
            }
        }
    }

    private fun addNull(result: xyz.znix.xftl.game.StoreData, shelfType: Int) {
        when (shelfType) {
            VanillaSaveFormat.SHELF_SYSTEM -> result.systems.add(null)
            VanillaSaveFormat.SHELF_WEAPON -> result.weapons.add(null)
            VanillaSaveFormat.SHELF_DRONE -> result.drones.add(null)
            VanillaSaveFormat.SHELF_AUGMENT -> result.augments.add(null)
            VanillaSaveFormat.SHELF_CREW -> result.crew.add(null)
        }
    }
}
